### PR TITLE
Fixes #8 (fixes logo files)

### LINKED ISSUE #8: Need to fix fix the issue "  return self.tk.call('wm', 'iconbitmap', self._w, bitmap)"

### PR DESCRIPTION
**Pull request by shiv10000**

### CODE REVIEW

**Comment by shiv10000** [comment]
193932733-d88e8080-16c8-44a8-9fca-c5661093190a

**Comment by shiv10000** [comment]
I have fixed this issue. There was some problem with the logo files.

**Comment by binbard** [comment]
No need to rename logo -> logo1
You should just add the modified logo files without editing other files in your commit

**Comment by WojciechSzade** [comment]
I'm pretty sure this problem was already solved by my previous pull #2

**Comment by shiv10000** [comment]
Ok again I will rename the file , but the problem was still there I have tried everything but once I modified the logo files everything back to normal.

**Pull request closed without merging**
